[workspace]
members = [
  "jvm",
  "libjvm",
  "crates/classfile",
  "crates/class-parser",
  "crates/vm",
  "tools/javap"
]

#https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
