[package]
name = "jvm"
version = "0.2.0"
authors = ["douchuan <1843657913@qq.com>"]
edition = "2021"

[dependencies]
clap = "3.0.0-beta.1"
env_logger = "0.8.2"
libjvm = { path = "../libjvm" }

[dev-dependencies]
libc = "0.2"
