[package]
name = "vm"
version = "0.1.0"
authors = ["Dou Chuan <1843657913@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bytes = "0.5.4"
chrono = "0.4.9"
classfile = { path = "../classfile", version = "0.1.0" }
class-parser = { path="../class-parser", version="0.1.0" }
dirs = "2.0.2"
lazy_static = "1.4.0"
libc = "0.2.71"
log = "0.4.0"
nix = "0.17.0"
zip = "0.5.4"

[profile.release]
lto = "fat"